class Config:
	SQLALCHEMY_DATABASE_URI='mysql+pymysql://root:lzh6682468@localhost:3306/blog?charset=utf8'
	SQLALCHEMY_COMMIT_ON_TEARDOWN=True
	SQLALCHEMY_TRACK_MODIFICATIONS=True
	SECRET_KEY='hard to guess string'
	FLASKY_POSTS_PER_PAGE=5

	
	def init_app(self,app):
		app.config['SQLALCHEMY_DATABASE_URI']=self.SQLALCHEMY_DATABASE_URI
		app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] =self.SQLALCHEMY_COMMIT_ON_TEARDOWN
		app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] =self.SQLALCHEMY_TRACK_MODIFICATIONS
		app.config['SECRET_KEY']=self.SECRET_KEY
		app.config['FLASKY_POSTS_PER_PAGE']=self.FLASKY_POSTS_PER_PAGE